---
title: "R Notebook"
output: html_notebook
---

Used Amazon Reviews Exporter in Google chrome to Extract Reviews:
https://chrome.google.com/webstore/detail/amazon-reviews-exporter-c/njlppnciolcibljfdobcefcngiampidm

Importing file into R
```{r}

#load packages into R
library(tm)         # text analytics - text mining
library(wordcloud)  # create wordcloud  
library(syuzhet)
library(lubridate)
library(ggplot2)
library(scales)
library(reshape2)
library(dplyr)

#import data into R
reviews <- read.csv(file.choose(), header = T)

str(reviews)

       
```

Creating Corpus
```{r}

# Create corpus
corpus <- iconv(reviews$text)
corpus <- Corpus(VectorSource(corpus))
inspect(corpus[1:5])

```

Cleaning Corpus
```{r}

#Clean text
corpus <- tm_map(corpus, tolower)
#inspect(corpus[1:5])

corpus <- tm_map(corpus, removePunctuation)
#inspect(corpus[1:5])

corpus <- tm_map(corpus, removeNumbers)
#inspect(corpus[1:5])

corpus <- tm_map(corpus, removeWords, stopwords("english"))
#inspect(corpus[1:5])

#Remove some common words not to used in text analysis - replace word 1, word 2 by actual words which needs to be replaced
#corpus <- tm_map(corpus, removeWords, c("word 1","word 2"))
#inspect(corpus[1:5])

corpus <- tm_map(corpus, stripWhitespace)
inspect(corpus[1:5])

reviews_final <- corpus

```


Create Term document
```{r}


#Term document matrix
tdm <- TermDocumentMatrix(reviews_final)
tdm <- as.matrix(tdm)
#tdm[1:10, 1:5]


```

Bar plot of words used more than 25 times in the product reviews
```{r}
#Bar plot

w <- rowSums(tdm)
w <- subset(w, w>=25)
#w
#barplot(w, las = 2)


```


Word Cloud
```{r}
# Word Cloud
w <- sort(rowSums(tdm), decreasing = T)
set.seed(2000)
wordcloud(words = names(w), 
          freq = w, 
          max.words = 50, 
          random.order = F, 
          min.freq = 5,
          colors = brewer.pal(25,"Dark2"),
          scale = c(5,0.5))



```

```{r}

#obtain sentiment scores
sentiment_data <- iconv(reviews$text)
s <- get_nrc_sentiment(sentiment_data)
#s[1:10,]

#calculate review wise score
s$score <- s$positive - s$negative

#write scores into a csv file
write.csv(x = s,file = "<csv file name with path>")

#check overall sentiment of the product
review_score <- colSums(s[,])
print(review_score)

```

```{r}
# Bar plot
barplot(colSums(s),
        las = 2,
        col = rainbow(10),
        ylab = 'Count',
        main = 'Sentiment')
```

